import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Flowbite theme={{ mode: 'dark' }}>
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className + ' bg-gray-50'}>{children}</body>
    </html>
    </Flowbite>
  );
}
